server:
  port: 80
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/java226rest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true

springdoc:
  swagger-ui:
    path: /xd
  api-docs:
    path: /api

benimmetnim:
  secret-key: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85


